### ISSUE TITLE
Fix issues discovered during PiT

### ISSUE THREAD

**Issue by pleku** [vaadin/osgi#22]
Mostly documentation clarifications, and some changes to the base starter (based on testing alpha3):

- [x] doc: I would change vaadin-core by vaadin in the 2nd snippet since it's the dependency used in starters (wizard)
- [x] doc: in 3rd snippet a <dependency> tag is missing
- [x] doc: in 3rd snippet ${flow.version} does not work, it's better remove that line and document that the version is comming from vaadin bom
- [x] doc: 6th snippet has a double comma before 'property ='
- [x] doc: 6th snippet should have imports, at least for Component, to avoid confussion with spring class
- [x] doc: InitParameters.SERVLET_PARAMETER_COMPATIBILITY_MODE does not exist 
- [x] project-base: InitParameters.SERVLET_PARAMETER_COMPATIBILITY_MODE comment in FixedVaadinServlet is wrong
- [x] doc: clarify which parts of vaadin cannot be used in OSGi, at least fussion-endpoint module (depends on spring)"

**Comment by mshabarov** [comment]
`clarify which parts of vaadin cannot be used in OSGi, at least fussion-endpoint module (depends on spring)` is already mentioned in OSGi limitations section https://github.com/vaadin/docs/blob/master/articles/flow/advanced/osgi-basic.asciidoc#limitations
