### ISSUE TITLE
PWA annotation does not work

### ISSUE THREAD

**Issue by mstahv** [vaadin/osgi#44]
At least the current situation in the [Karaf example](https://github.com/vaadin/base-starter-flow-karaf) is that no service worker or icons are present, even though the annotation is used in the example. We should fix this (preferably) or announce it as a limitation for OSGi apps.

**Comment by denis-anisimov** [comment]
This is a mixture of problems in various problems.

PWA support is not ready to the fact that PWA annotated class may appear at any time (it assumes that when the application is started the PWA configuration is already available). So PWA support in Flow is not OSGi ready .

`AppShellRegistry` is not OSGi ready as well. `AppShellRegistry` assumes that `AppShellConfigurator`  classes which are passed into `VaadinAppShellInitializer`  are all inside the web app.
This is wrong. `VaadinAppShellInitializer` is called with ALL classes available at the moment inside OSGi container.
So there can be several  `AppShellConfigurator`   classes in various web applications. But only one (or few)  `AppShellConfigurator`  per web app.
So `AppShellRegistry::isShell` impl requires significant changes.

There can be other problems inside PWA internal code as well. It's hard to say at the moment whether there are other issues.

So at the moment PWA is completely broken in OSGi
