### ISSUE TITLE
bnd tools test hardcode flow version in its app.bnd file

### ISSUE THREAD

**Issue by denis-anisimov** [vaadin/osgi#70]
Flow version should be takes from a parameter to be able to run validation against different Flow versions.
It should not be hardcoded.

**Comment by ZheSun88** [comment]
similar implementation has been used in platform 
https://github.com/vaadin/platform/blob/master/vaadin-platform-servlet-containers-tests/bnd-tools-test/app.bndrun#L33...L39 

Can you take a look at the same time?
